@startuml cerrarSesion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible
package cerrarSesion as "cerrarSesion()" {
    rectangle #629EF9 CerrarSesionView
    rectangle #b5bd68 CerrarSesionController
    rectangle #F2AC4E SesionRepository
    rectangle #F2AC4E Sesion
    rectangle #F2AC4E Usuario
}

rectangle #CDEBA5 ":SESION_CERRADA" as SESIONCERRADA

SistemaDisponible -r-> CerrarSesionView: cerrarSesion()

CerrarSesionView -d-> CerrarSesionController: solicitarCierre()

CerrarSesionController --> Sesion: getUsuario() : Usuario
CerrarSesionController --> CerrarSesionView: mostrarConfirmacion(usuario)
CerrarSesionView -d-> CerrarSesionController: confirmarCierre()
CerrarSesionController --> SesionRepository: terminarSesion(sesion)
SesionRepository --> Sesion: destruirSesion()

Sesion -d- Usuario

CerrarSesionView ..> SistemaDisponible: cancelarCierre()
CerrarSesionView ..r.> SESIONCERRADA: confirmarCierre()

@enduml