@startuml importarConfiguracionGlobal-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible
package importarConfiguracionGlobal as "importarConfiguracionGlobal()" {
    rectangle #629EF9 ImportarConfiguracionGlobalView
    rectangle #b5bd68 ImportarConfiguracionGlobalController
    rectangle #F2AC4E GradoRepository
    rectangle #F2AC4E AsignaturaRepository
    rectangle #F2AC4E AlumnoRepository
    rectangle #F2AC4E PreguntaRepository
}

rectangle #CDEBA5 ":Collaboration ImportarGrados" as ImportarGrados
rectangle #CDEBA5 ":Collaboration ImportarAsignaturas" as ImportarAsignaturas
rectangle #CDEBA5 ":Collaboration ImportarAlumnos" as ImportarAlumnos
rectangle #CDEBA5 ":Collaboration ImportarPreguntas" as ImportarPreguntas

SistemaDisponible -r-> ImportarConfiguracionGlobalView : importarConfiguracionGlobal(config)

ImportarConfiguracionGlobalView -d-> ImportarConfiguracionGlobalController: iniciarImportacion(config)

ImportarConfiguracionGlobalController --> AlumnoRepository: añadirAlumnos(alumnos) : void
ImportarConfiguracionGlobalController --> GradoRepository: añadirGrados(grados) : void
ImportarConfiguracionGlobalController --> AsignaturaRepository: añadirAsignaturas(asignaturas) :void
ImportarConfiguracionGlobalController --> PreguntaRepository: añadirPreguntas(preguntas) : void

ImportarConfiguracionGlobalView ..> ImportarGrados: importarGrados()
ImportarConfiguracionGlobalView ..> ImportarAsignaturas: importarAsignaturas()
ImportarConfiguracionGlobalView ..> ImportarAlumnos: importarAlumnos()
ImportarConfiguracionGlobalView ..> ImportarPreguntas: importarPreguntas()

ImportarConfiguracionGlobalView -u-> SistemaDisponible: cancelarImportacion() / salir()

@enduml